### ISSUE TITLE
As a coordinator I can get report with all the cities in a continent organised by largest population to smallest so that I can prepare factsheets for the operation team

### ISSUE THREAD

**Issue by oparatte** [oparatte/SET08803-Group1#23]

**Comment by amit169** [comment]
Report is generated 
<img width="330" alt="Screenshot 2022-02-16 at 14 23 56" src="https://user-images.githubusercontent.com/16576609/154252185-4d66332a-e84a-48d7-b18a-be784327478d.png">

**Comment by oparatte** [comment]
@amit169, Can you update the screenshot (the one attached is for issue 16 - Requirement 1)?
