### ISSUE TITLE
Missing fields in "All the countries in the world" report (use case 1)

### ISSUE THREAD

**Issue by oparatte** [oparatte/SET08803-Group1#51]
Reports currently includes Country and Population.

A country report requires the following columns:
* Code
* Name
* Continent
* Region
* Population
* Capital

**Comment by Chris1429** [comment]
![countries.PNG](https://zube.io/files/set08803-group1/918c778098c53a58baa9f8679be6ac21-countries.png)

**Comment by Chris1429** [comment]
![countries.PNG](https://zube.io/files/set08803-group1/918c778098c53a58baa9f8679be6ac21-countries.png)
